### ISSUE TITLE
Does not work with all coordinates

### ISSUE THREAD

**Issue by blbates** [robintw/LatLongToWRS#1]
> > > import get_wrs
> > > conv = get_wrs.ConvertToWRS()
> > > conv.get_wrs(-93.3702778, 37.16852778)
> > > []

The code only seems to work with a specific range of coordinates.

**Comment by robintw** [comment]
The problem here is that the co-ordinates must be given as latitude followed by longitude. `-93.37` is not a valid latitude (as latitude only goes from `-90` to `+90`), so it doesn't give any result.

Running it the opposite way around (`conv.get_wrs(37.16852778, -93.3702778)` should give you the right answer.

There are also some situations where there will not be any results because there are some places on the Earth (particularly around the poles) which aren't covered by Landsat.

**Comment by blbates** [comment]
Thanks a lot for the speedy reply!
